language: go

services:
  - docker

go:
  - 1.13.x

script:
  - go fmt
  - go test
  - CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o server .
  - docker build -t danbelling/supermarket-api .

after_success:
  - ./publish.sh

notifications:
  email:
    recipients:
      - danhbelling@gmail.com
    on_success: always